<template>
  <div id="app">
    <VueNestable v-model="nestableItems" childrenProp="sub_categories" rtl>
      <VueNestableHandle slot-scope="{ item }" :item="item">
        <i class="fas fa-user" />
        {{ item.name }}
      </VueNestableHandle>
    </VueNestable>
  </div>
</template>

<script>
import { VueNestable, VueNestableHandle } from "vue-nestable";

export default {
  name: "App",
  components: {
    VueNestable,
    VueNestableHandle,
  },
  data() {
    return {
      nestableItems: [
        {
          id: 424,
          name: "أثاث",
          slug: "أثاث",
          SEO_category_title: "أثاث",
          SEO_category_description:
            "السلام عليكم السلام عليكم السلام عليكم السلام عليكم السلام عليكم السلام عليكم السلام عليكم السلام عليكم السلام عليكم السلام",
          names: { en: "furniture", ar: "أثاث" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/أثاث",
          image:
            "https://zid-testing.s3.eu-west-1.amazonaws.com/3dfc16e6-ad19-4126-9c2a-5e4a7fb73051/60f86a24-614c-47dd-a187-26344b56befd-260x260.png",
          img_alt_text: null,
          products_count: 3,
          sub_categories: [],
          parent_id: null,
          flat_name: "أثاث",
          is_published: true,
        },
        {
          id: 550,
          name: "accessories",
          slug: "accessories",
          SEO_category_title: "accessories",
          SEO_category_description: "",
          names: { en: "", ar: "accessories" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/accessories",
          image:
            "https://zid-testing.s3.eu-west-1.amazonaws.com/3dfc16e6-ad19-4126-9c2a-5e4a7fb73051/d5c8b647-0686-412c-8187-74ab73f350ff-260x260.png",
          img_alt_text: null,
          products_count: 0,
          sub_categories: [],
          parent_id: null,
          flat_name: "accessories",
          is_published: false,
        },
        {
          id: 554,
          name: "موبيلات",
          slug: "موبيلات",
          SEO_category_title: "موبيلات",
          SEO_category_description: "هواتف",
          names: { en: null, ar: "موبيلات" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/موبيلات",
          image: null,
          img_alt_text: null,
          products_count: 4,
          sub_categories: [],
          parent_id: null,
          flat_name: "موبيلات",
          is_published: true,
        },
        {
          id: 447,
          name: "Weight Test",
          slug: "sub-weight",
          SEO_category_title: "Weight Test",
          SEO_category_description:
            "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة ع stetsttaa",
          names: { en: "Weight Test", ar: "Weight Test" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/sub-weight",
          image:
            "https://zid-testing.s3.eu-west-1.amazonaws.com/3dfc16e6-ad19-4126-9c2a-5e4a7fb73051/25757d8a-77e7-4ab3-b198-66128e902ddb-260x260.jpeg",
          img_alt_text: "هذا النص هو مثال لنص يمكن أن يستبدل",
          products_count: 9,
          sub_categories: [],
          parent_id: null,
          flat_name: "Weight Test",
          is_published: true,
        },
        {
          id: 453,
          name: "الورد البلدى",
          slug: "الورد-البلدى",
          SEO_category_title: "الورد البلدى",
          SEO_category_description: "ok this a yesy",
          names: { en: "", ar: "الورد البلدى" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/الورد-البلدى",
          image: null,
          img_alt_text: null,
          products_count: 0,
          sub_categories: [],
          parent_id: null,
          flat_name: "الورد البلدى",
          is_published: true,
        },
        {
          id: 229,
          name: "عطور",
          slug: "عطور-تيست-يوم-الخميس",
          SEO_category_title: "عنوان صفحة التصنيف تيست",
          SEO_category_description: "وصف صفحة التصنيف تيست",
          names: { en: null, ar: "عطور" },
          description: null,
          url:
            "https://testing-catalog.zid.sa/osama/categories/عطور-تيست-يوم-الخميس",
          image:
            "https://zid-testing.s3.eu-west-1.amazonaws.com/3dfc16e6-ad19-4126-9c2a-5e4a7fb73051/5494c6ab-580a-4b6d-bad0-a19e01cb0c10-260x260.jpeg",
          img_alt_text: null,
          products_count: 6,
          sub_categories: [
            {
              id: 230,
              name: "رجالي",
              slug: "testرجالي",
              SEO_category_title: "testرجالي",
              SEO_category_description: "new test",
              names: { en: null, ar: "رجالي" },
              description: null,
              url: "https://testing-catalog.zid.sa/osama/categories/testرجالي",
              image: null,
              img_alt_text: null,
              products_count: 0,
              sub_categories: [],
              parent_id: 229,
              flat_name: "عطور - رجالي",
              is_published: false,
            },
          ],
          parent_id: null,
          flat_name: "عطور",
          is_published: true,
        },
        {
          id: 207,
          name: "الحقائب",
          slug: "الحقائب",
          SEO_category_title: "الحقائب",
          SEO_category_description: "",
          names: { ar: "الحقائب" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/الحقائب",
          image: null,
          img_alt_text: null,
          products_count: 5,
          sub_categories: [],
          parent_id: null,
          flat_name: "الحقائب",
          is_published: true,
        },
        {
          id: 410,
          name: "جلابية،فقطان",
          slug: "جلابيةفقطان",
          SEO_category_title: "جلابية،فقطان",
          SEO_category_description: "",
          names: { ar: "جلابية،فقطان" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/جلابيةفقطان",
          image: null,
          img_alt_text: null,
          products_count: 0,
          sub_categories: [],
          parent_id: null,
          flat_name: "جلابية،فقطان",
          is_published: true,
        },
        {
          id: 419,
          name: "قسم المنتجات اليدوية",
          slug: "قسم-المنتجات-اليدوية",
          SEO_category_title: "categorytitle",
          SEO_category_description:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias atque illo nostrum quisquam repellendus. Aut cupiditate dolorum ducimus earum et minus necessitatibus non nostrum officia, quis quod quos recusandae saepe.",
          names: { en: "handmade products", ar: "قسم المنتجات اليدوية" },
          description: null,
          url:
            "https://testing-catalog.zid.sa/osama/categories/قسم-المنتجات-اليدوية",
          image: null,
          img_alt_text: "alt text of main  image",
          products_count: 7,
          sub_categories: [],
          parent_id: null,
          flat_name: "قسم المنتجات اليدوية",
          is_published: true,
        },
        {
          id: 409,
          name: "خدمات",
          slug: "خدمات",
          SEO_category_title: "خدمات",
          SEO_category_description: "",
          names: { en: "Services", ar: "خدمات" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/خدمات",
          image:
            "https://zid-testing.s3.eu-west-1.amazonaws.com/3dfc16e6-ad19-4126-9c2a-5e4a7fb73051/ee6bccc4-f217-46d7-a672-2050b561f0d4-260x260.jpeg",
          img_alt_text: null,
          products_count: 12,
          sub_categories: [
            {
              id: 231,
              name: "نسائي",
              slug: "woman-access",
              SEO_category_title: "seoنسائي",
              SEO_category_description: "",
              names: { en: null, ar: "نسائي" },
              description: null,
              url:
                "https://testing-catalog.zid.sa/osama/categories/woman-access",
              image: null,
              img_alt_text: null,
              products_count: 3,
              sub_categories: [
                {
                  id: 206,
                  name: "dogs",
                  slug: "new-dogs",
                  SEO_category_title: "dogs",
                  SEO_category_description: "",
                  names: { en: "dogs", ar: "dogs" },
                  description: null,
                  url:
                    "https://testing-catalog.zid.sa/osama/categories/new-dogs",
                  image:
                    "https://zid-testing.s3.eu-west-1.amazonaws.com/3dfc16e6-ad19-4126-9c2a-5e4a7fb73051/b305015d-ef57-4b81-bdb1-45544b51ee52-260x260.png",
                  img_alt_text: null,
                  products_count: 2,
                  sub_categories: [],
                  parent_id: 231,
                  flat_name: "خدمات - نسائي - dogs",
                  is_published: true,
                },
              ],
              parent_id: 409,
              flat_name: "خدمات - نسائي",
              is_published: true,
            },
            {
              id: 412,
              name: "جوالات",
              slug: "جوالات",
              SEO_category_title: "جوالات",
              SEO_category_description: "",
              names: { en: null, ar: "جوالات" },
              description: null,
              url: "https://testing-catalog.zid.sa/osama/categories/جوالات",
              image: null,
              img_alt_text: null,
              products_count: 2,
              sub_categories: [],
              parent_id: 409,
              flat_name: "خدمات - جوالات",
              is_published: true,
            },
          ],
          parent_id: null,
          flat_name: "خدمات",
          is_published: true,
        },
        {
          id: 418,
          name: "اكسسوارات",
          slug: "اكسسوارات",
          SEO_category_title: "اكسسوارات",
          SEO_category_description: "",
          names: { ar: "اكسسوارات" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/اكسسوارات",
          image: null,
          img_alt_text: null,
          products_count: 6,
          sub_categories: [],
          parent_id: null,
          flat_name: "اكسسوارات",
          is_published: true,
        },
        {
          id: 417,
          name: "tshirts",
          slug: "tshirts",
          SEO_category_title: "tshirts",
          SEO_category_description: "",
          names: { ar: "tshirts" },
          description: null,
          url: "https://testing-catalog.zid.sa/osama/categories/tshirts",
          image: null,
          img_alt_text: null,
          products_count: 1,
          sub_categories: [],
          parent_id: null,
          flat_name: "tshirts",
          is_published: true,
        },
      ],
    };
  },
};
</script>

<style>
</style>
